---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7
  - name: osx-sierra
  - name: windows-2012r2
    driver:
      name: vagrant
      customize:
        rtcuseutc: "off"
    transport:
      name: winrm
    attributes:
      test_owner: 'Administrator'

<% s3 = YAML.load(ERB.new(IO.read('.s3.yml')).result) %>
suites:
  - name: default
    run_list:
      - recipe[remote_file_s3_test::default]
    attributes:
      remote_file_s3_test:
        aws_access_key_id: <%= s3['access_key_id'] %>
        aws_secret_access_key: <%= s3['secret_access_key'] %>
        region:
        bucket: <%= s3['bucket'] %>
        file: <%= s3['file'] %>
